// login
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// Register
export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE";

// logout
export const LOGOUT = "LOGOUT"

// Edit profile
export const EDIT_PROFILE_START = "EDIT_PROFILE_START"
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS"
export const EDIT_PROFILE_FAILURE = "EDIT_PROFILE_FAILURE"

// Update avatar
export const UPDATE_AVATAR_START = "UPDATE_AVATAR_START"
export const UPDATE_AVATAR_SUCCESS = "UPDATE_AVATAR_SUCCESS"
export const UPDATE_AVATAR_FAILURE = "UPDATE_AVATAR_FAILURE"