// Get posts
export const GET_POSTS_START = 'GET_POSTS_START'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE'

// Get details post
export const GET_DETAILS_START = 'GET_DETAILS_START'
export const GET_DETAILS_SUCCESS = 'GET_DETAILS_SUCCESS'
export const GET_DETAILS_FAILURE = 'GET_DETAILS_FAILURE'

// Get posts by UserId
export const GET_POSTS_USER_ID_START = 'GET_POSTS_USER_ID_START'
export const GET_POSTS_USER_ID_SUCCESS = 'GET_POSTS_USER_ID_SUCCESS'
export const GET_POSTS_USER_ID_FAILURE = 'GET_POSTS_USER_ID_FAILURE'

// Create posts
export const CREATE_POST_START = 'CREATE_POST_START'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE'

// Update post 
export const UPDATE_POST_START = 'UPDATE_POST_START'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAILURE = 'UPDATE_POST_FAILURE'

// Delete post
export const DELETE_POST_START = 'DELETE_POST_START'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE'

// Like post
export const LIKE_POST_START = 'LIKE_POST_START'
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'
export const LIKE_POST_FAILURE = 'LIKE_POST_FAILURE'

// Comment post
export const COMMENT_POST_START = 'COMMENT_POST_START'
export const COMMENT_POST_SUCCESS = 'COMMENT_POST_SUCCESS'
export const COMMENT_POST_FAILURE = 'COMMENT_POST_FAILURE'
