// Find user
export const FIND_USERS_START = 'FIND_USERS_START'
export const FIND_USERS_SUCCESS = 'FIND_USERS_SUCCESS'
export const FIND_USERS_FAILURE = 'FIND_USERS_FAILURE'

// Get user by id
export const GET_USER_BY_ID_START = 'GET_USER_BY_ID_START'
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS'
export const GET_USER_BY_ID_FAILURE = 'GET_USER_BY_ID_FAILURE'

// Check follow user
export const CHECK_FOLLOW_USER_START = 'CHECK_FOLLOW_USER_START'
export const CHECK_FOLLOW_USER_SUCCESS = 'CHECK_FOLLOW_USER_SUCCESS'
export const CHECK_FOLLOW_USER_FAILURE = 'CHECK_FOLLOW_USER_FAILURE'

// Follow user
export const FOLLOW_USER_START = 'FOLLOW_USER_START'
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS'
export const FOLLOW_USER_FAILURE = 'FOLLOW_USER_FAILURE'

// UnFollow
export const UNFOLLOW_USER_START = 'UNFOLLOW_USER_START'
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS'
export const UNFOLLOW_USER_FAILURE = 'UNFOLLOW_USER_FAILURES'